project:
  type: website

website:
  title: "metaodi"
  site-url: https://metaodi.ch
  description: "Personal website of Stefan Oderbolz"
  favicon: assets/favicon.png
  image: assets/titlecard.png
  twitter-card: true
  open-graph: true
  draft-mode: unlinked
  repo-url: https://github.com/metaodi/metaodi.github.io
  repo-actions: [edit, issue]
  navbar:
    left: 
      - text: About
        href: about.qmd

  search:
    location: navbar
    type: overlay

format:
  html:
    theme: [default, custom.scss]
    mainfont: Merriweather
    include-in-header:
      - file: font.html

execute:
  freeze: auto
